// <auto-generated />
using System;
using KairosPayHub.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KairosPayHub.Api.Data.Migrations
{
    [DbContext(typeof(KairosDbContext))]
    [Migration("20260808161724_AddContributionsDropRecords")]
    partial class AddContributionsDropRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KairosPayHub.Api.Auth.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Auth.EmailConfirmationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Code");

                    b.ToTable("email_confirmation_codes", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Auth.OneTimeToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.HasIndex("TokenHash", "Purpose");

                    b.ToTable("one_time_tokens", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .HasFilter("\"Revoked\" = false");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Revoked");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Church", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("churches", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Giving.Contribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByAuthUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("GHS");

                    b.Property<DateTimeOffset>("DateSent")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EnteredByAuthUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberParentNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectedReason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("MemberParentNodeId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("ProgramId", "Status");

                    b.ToTable("contributions", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Giving.GivingProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByAuthUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("GivingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PeriodLabel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ScopeKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ScopeNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("ChurchId", "Status");

                    b.HasIndex("ChurchId", "GivingType", "PeriodLabel", "ScopeKind")
                        .IsUnique()
                        .HasFilter("\"ScopeKind\" = 'ChurchWide'");

                    b.ToTable("giving_programs", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Giving.GivingProgramScopeNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StructureNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.HasIndex("ProgramId", "StructureNodeId")
                        .IsUnique();

                    b.ToTable("giving_program_scope_nodes", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.Cell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FellowshipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("ChurchId", "Id");

                    b.HasIndex("FellowshipId");

                    b.HasIndex("ChurchId", "FellowshipId");

                    b.ToTable("structure_cells", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.Church", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("church_tenants", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.Fellowship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PfccId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("PfccId");

                    b.ToTable("structure_fellowships", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AuthUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OccupationStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("ParentNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Residence")
                        .HasColumnType("text");

                    b.Property<string>("SchoolOrWorkplace")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId");

                    b.HasIndex("ChurchId");

                    b.HasIndex("ParentNodeId");

                    b.HasIndex("ChurchId", "Email");

                    b.HasIndex("ChurchId", "ParentNodeId");

                    b.ToTable("church_members", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.Pfcc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.ToTable("pfccs", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ScopeCellId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScopeFellowshipId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScopeNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScopePfccId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId");

                    b.HasIndex("ChurchId");

                    b.HasIndex("ScopeCellId");

                    b.HasIndex("ScopeFellowshipId");

                    b.HasIndex("ScopeNodeId");

                    b.HasIndex("ScopePfccId");

                    b.HasIndex("ChurchId", "AuthUserId");

                    b.HasIndex("ChurchId", "Role");

                    b.HasIndex("ChurchId", "ScopeNodeId");

                    b.ToTable("role_assignments", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.StructureLayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StandardType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "SortOrder")
                        .IsUnique();

                    b.ToTable("structure_layers", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.StructureNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LeaderMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("LayerId");

                    b.HasIndex("LeaderMemberId");

                    b.HasIndex("ParentNodeId");

                    b.HasIndex("ChurchId", "LayerId");

                    b.HasIndex("ChurchId", "ParentNodeId");

                    b.ToTable("structure_nodes", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.StructureTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId")
                        .IsUnique();

                    b.ToTable("structure_templates", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthSubject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthSubject")
                        .IsUnique();

                    b.HasIndex("ChurchId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Church", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Organization", "Organization")
                        .WithMany("Churches")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Giving.Contribution", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KairosPayHub.Api.Domain.Giving.GivingProgram", "Program")
                        .WithMany("Contributions")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Giving.GivingProgram", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.Church", "Church")
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Church");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Giving.GivingProgramScopeNode", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Giving.GivingProgram", "Program")
                        .WithMany("ScopeNodes")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.Cell", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.Church", "Church")
                        .WithMany("Cells")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KairosPayHub.Api.Domain.Structure.Fellowship", "Fellowship")
                        .WithMany("Cells")
                        .HasForeignKey("ChurchId", "FellowshipId")
                        .HasPrincipalKey("ChurchId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Church");

                    b.Navigation("Fellowship");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.Fellowship", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.Church", "Church")
                        .WithMany("Fellowships")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KairosPayHub.Api.Domain.Structure.Pfcc", "Pfcc")
                        .WithMany("Fellowships")
                        .HasForeignKey("PfccId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Church");

                    b.Navigation("Pfcc");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.Member", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.Church", "Church")
                        .WithMany("Members")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KairosPayHub.Api.Domain.Structure.StructureNode", "ParentNode")
                        .WithMany("Members")
                        .HasForeignKey("ChurchId", "ParentNodeId")
                        .HasPrincipalKey("ChurchId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Church");

                    b.Navigation("ParentNode");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.Pfcc", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.Church", "Church")
                        .WithMany("Pfccs")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Church");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.RoleAssignment", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.Church", "Church")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KairosPayHub.Api.Domain.Structure.Cell", "ScopeCell")
                        .WithMany()
                        .HasForeignKey("ScopeCellId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KairosPayHub.Api.Domain.Structure.Fellowship", "ScopeFellowship")
                        .WithMany()
                        .HasForeignKey("ScopeFellowshipId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KairosPayHub.Api.Domain.Structure.StructureNode", "ScopeNode")
                        .WithMany()
                        .HasForeignKey("ScopeNodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KairosPayHub.Api.Domain.Structure.Pfcc", "ScopePfcc")
                        .WithMany()
                        .HasForeignKey("ScopePfccId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Church");

                    b.Navigation("ScopeCell");

                    b.Navigation("ScopeFellowship");

                    b.Navigation("ScopeNode");

                    b.Navigation("ScopePfcc");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.StructureLayer", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.StructureTemplate", "Template")
                        .WithMany("Layers")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.StructureNode", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.Church", "Church")
                        .WithMany("Nodes")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KairosPayHub.Api.Domain.Structure.StructureLayer", "Layer")
                        .WithMany("Nodes")
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KairosPayHub.Api.Domain.Structure.Member", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KairosPayHub.Api.Domain.Structure.StructureNode", "ParentNode")
                        .WithMany("Children")
                        .HasForeignKey("ChurchId", "ParentNodeId")
                        .HasPrincipalKey("ChurchId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Church");

                    b.Navigation("Layer");

                    b.Navigation("Leader");

                    b.Navigation("ParentNode");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.StructureTemplate", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.Church", "Church")
                        .WithOne("Template")
                        .HasForeignKey("KairosPayHub.Api.Domain.Structure.StructureTemplate", "ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Church");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.User", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Church", "Church")
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KairosPayHub.Api.Domain.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Church");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("KairosPayHub.Api.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("KairosPayHub.Api.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KairosPayHub.Api.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("KairosPayHub.Api.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Giving.GivingProgram", b =>
                {
                    b.Navigation("Contributions");

                    b.Navigation("ScopeNodes");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Organization", b =>
                {
                    b.Navigation("Churches");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.Church", b =>
                {
                    b.Navigation("Cells");

                    b.Navigation("Fellowships");

                    b.Navigation("Members");

                    b.Navigation("Nodes");

                    b.Navigation("Pfccs");

                    b.Navigation("RoleAssignments");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.Fellowship", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.Pfcc", b =>
                {
                    b.Navigation("Fellowships");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.StructureLayer", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.StructureNode", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.StructureTemplate", b =>
                {
                    b.Navigation("Layers");
                });
#pragma warning restore 612, 618
        }
    }
}
