// <auto-generated />
using System;
using KairosPayHub.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KairosPayHub.Api.Data.Migrations
{
    [DbContext(typeof(KairosDbContext))]
    [Migration("20260924004103_AddOutreachSentMessage")]
    partial class AddOutreachSentMessage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KairosPayHub.Api.Auth.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Auth.EmailConfirmationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Code");

                    b.ToTable("email_confirmation_codes", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Auth.OneTimeToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.HasIndex("TokenHash", "Purpose");

                    b.ToTable("one_time_tokens", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .HasFilter("\"Revoked\" = false");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Revoked");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Account.UserTablePreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ColumnsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId");

                    b.HasIndex("AuthUserId", "Key")
                        .IsUnique();

                    b.ToTable("user_table_preferences", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Administrators.ChurchAdministrator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AffiliationKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AuthUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByAuthUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeactivatedByAuthUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId");

                    b.HasIndex("ChurchId");

                    b.HasIndex("Email");

                    b.HasIndex("MemberId");

                    b.HasIndex("ChurchId", "AuthUserId")
                        .IsUnique();

                    b.ToTable("church_administrators", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Attendance.AttendanceCellInvitee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CellScopeNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GraduatedMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InvitedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFirstTimer")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OccupationStatus")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("PriorChurchAttendance")
                        .HasColumnType("text");

                    b.Property<string>("Residence")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SchoolOrWorkplace")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("GraduatedMemberId");

                    b.HasIndex("InvitedByMemberId");

                    b.HasIndex("ChurchId", "CellScopeNodeId", "IsActive");

                    b.ToTable("attendance_cell_invitees", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Attendance.AttendanceEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AutoMarkedAbsentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("MarkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MarkedByAuthUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberScopeNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OccurrenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("OccurrenceId");

                    b.HasIndex("OccurrenceId", "MemberId")
                        .IsUnique();

                    b.ToTable("attendance_entries", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Attendance.AttendanceFirstTimer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OccurrenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("ScopeNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OccurrenceId", "ScopeNodeId");

                    b.ToTable("attendance_first_timers", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Attendance.AttendanceInviteeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InviteeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OccurrenceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScopeNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WasFirstTimer")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("InviteeId");

                    b.HasIndex("OccurrenceId", "InviteeId")
                        .IsUnique();

                    b.ToTable("attendance_invitee_entries", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Attendance.AttendanceMeetingPack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentFingerprint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("OccurrenceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PublishedByAuthUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OccurrenceId")
                        .IsUnique();

                    b.ToTable("attendance_meeting_packs", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Attendance.AttendanceMeetingPackFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<Guid>("PackId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("PackId");

                    b.ToTable("attendance_meeting_pack_files", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Attendance.AttendanceMeetingPackReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DownloadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PackId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PackId", "AuthUserId")
                        .IsUnique();

                    b.ToTable("attendance_meeting_pack_receipts", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Attendance.AttendanceMeetingType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AutoGenerateWeeksAhead")
                        .HasColumnType("integer");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByAuthUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("DeadlineDayOffset")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("DeadlineTimeUtc")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAlwaysOpen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("OpensDayOffset")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("OpensTimeUtc")
                        .HasColumnType("time without time zone");

                    b.Property<string>("RecurrenceKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReportSchema")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<bool>("RequiresReport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ScopeKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ScopeNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubmissionLayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("SubmissionLayerId");

                    b.ToTable("attendance_meeting_types", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Attendance.AttendanceMeetingTypeScopeNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MeetingTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StructureNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MeetingTypeId");

                    b.HasIndex("MeetingTypeId", "StructureNodeId")
                        .IsUnique();

                    b.ToTable("attendance_meeting_type_scope_nodes", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Attendance.AttendanceOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExcusedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ExcusedByAuthUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExcusedReason")
                        .HasColumnType("text");

                    b.Property<DateOnly>("MeetingDate")
                        .HasColumnType("date");

                    b.Property<Guid>("MeetingTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SubmissionDeadlineAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("SubmissionOpensAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("MeetingTypeId");

                    b.HasIndex("MeetingTypeId", "MeetingDate")
                        .IsUnique();

                    b.ToTable("attendance_occurrences", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Attendance.AttendanceScopeSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByAuthUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedLeaderAuthUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("EnteredByRole")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("GraceDeadlineAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuestRiskLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("clear");

                    b.Property<string>("GuestRiskReasons")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("LockStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OccurrenceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RejectedByAuthUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReopenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReopenedByAuthUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReportPayload")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ScopeNodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SubmittedByAuthUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OccurrenceId");

                    b.HasIndex("OccurrenceId", "ScopeNodeId")
                        .IsUnique();

                    b.ToTable("attendance_scope_submissions", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Authorization.ChurchAbilityOverlay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ability")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("ChurchId", "SubjectKind", "SubjectId", "Ability")
                        .IsUnique();

                    b.ToTable("church_ability_overlays", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Church", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("churches", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Events.ChurchCalendarEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByAuthUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("ScopeNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScopeNodeId");

                    b.HasIndex("ChurchId", "EventDate");

                    b.ToTable("church_calendar_events", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Giving.Contribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByAuthUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("GHS");

                    b.Property<DateTimeOffset>("DateSent")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EnteredByAuthUserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("EnteredByRole")
                        .HasColumnType("integer");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberParentNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectedReason")
                        .HasColumnType("text");

                    b.Property<int?>("RemittanceMedium")
                        .HasColumnType("integer");

                    b.Property<string>("RemittanceMediumOther")
                        .HasColumnType("text");

                    b.Property<bool?>("SentToPastor")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("MemberId");

                    b.HasIndex("MemberParentNodeId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("ProgramId", "BatchId");

                    b.HasIndex("ProgramId", "Status");

                    b.ToTable("contributions", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Giving.GivingProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByAuthUserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CreatedByRole")
                        .HasColumnType("integer");

                    b.Property<string>("CustomTypeLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EventDate")
                        .HasColumnType("date");

                    b.Property<string>("GivingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("GoLiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeadersNotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LogOpensAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentProgramId")
                        .HasColumnType("uuid");

                    b.Property<string>("PeriodLabel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("ReceiveGivingsOnMain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByAuthUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ScopeNodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("StartsOn")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("ParentProgramId");

                    b.HasIndex("ChurchId", "ApprovalStatus");

                    b.HasIndex("ChurchId", "ParentProgramId");

                    b.HasIndex("ChurchId", "Status");

                    b.HasIndex("ChurchId", "Status", "GoLiveAt");

                    b.HasIndex("ChurchId", "GivingType", "PeriodLabel", "ScopeKind")
                        .IsUnique()
                        .HasFilter("\"ScopeKind\" = 'ChurchWide' AND \"ParentProgramId\" IS NULL");

                    b.ToTable("giving_programs", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Giving.GivingProgramScopeNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StructureNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.HasIndex("ProgramId", "StructureNodeId")
                        .IsUnique();

                    b.ToTable("giving_program_scope_nodes", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Media.ChurchServiceRecording", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BunnyVideoGuid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByAuthUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomThumbnailUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RetentionExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ServiceDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("StorageBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BunnyVideoGuid")
                        .IsUnique();

                    b.HasIndex("CategoryId");

                    b.HasIndex("ChurchId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("ChurchId", "PublishedAt");

                    b.ToTable("church_service_recordings", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Media.ServiceRecordingCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("ChurchId", "Name")
                        .IsUnique();

                    b.ToTable("service_recording_categories", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Media.ServiceRecordingSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("ChurchId", "Name")
                        .IsUnique();

                    b.ToTable("service_recording_series", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinkPath")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipientAuthUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId", "RecipientAuthUserId");

                    b.HasIndex("RecipientAuthUserId", "ReadAt", "CreatedAt");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Notifications.WebPushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("AuthUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.HasIndex("AuthUserId", "ChurchId");

                    b.ToTable("push_subscriptions", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Outreach.OutreachAreaCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RadiusMiles")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("SearchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("City", "State", "RadiusMiles")
                        .IsUnique();

                    b.ToTable("outreach_area_caches", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Outreach.OutreachChurch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailSourceUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlaceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("RadiusMiles")
                        .HasColumnType("double precision");

                    b.Property<bool>("Saved")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SentBody")
                        .HasColumnType("text");

                    b.Property<string>("SentSubject")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId")
                        .IsUnique();

                    b.ToTable("outreach_churches", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Outreach.SuperadminOperator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("superadmin_operators", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.Cell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FellowshipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("ChurchId", "Id");

                    b.HasIndex("FellowshipId");

                    b.HasIndex("ChurchId", "FellowshipId");

                    b.ToTable("structure_cells", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.Church", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ApproximateMemberCount")
                        .HasColumnType("integer");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("GHS");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryPastorName")
                        .HasColumnType("text");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("UTC");

                    b.HasKey("Id");

                    b.ToTable("church_tenants", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.Fellowship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PfccId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("PfccId");

                    b.ToTable("structure_fellowships", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AuthUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OccupationStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("ParentNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Residence")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Responsiveness")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<string>("RosterStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchoolOrWorkplace")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("State")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Workplace")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId");

                    b.HasIndex("ChurchId");

                    b.HasIndex("ParentNodeId");

                    b.HasIndex("ChurchId", "Email");

                    b.HasIndex("ChurchId", "ParentNodeId");

                    b.ToTable("church_members", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.Pfcc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.ToTable("pfccs", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPrimaryPastor")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ScopeCellId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScopeFellowshipId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScopeNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScopePfccId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId");

                    b.HasIndex("ChurchId");

                    b.HasIndex("ScopeCellId");

                    b.HasIndex("ScopeFellowshipId");

                    b.HasIndex("ScopeNodeId");

                    b.HasIndex("ScopePfccId");

                    b.HasIndex("ChurchId", "AuthUserId");

                    b.HasIndex("ChurchId", "Role");

                    b.HasIndex("ChurchId", "ScopeNodeId");

                    b.ToTable("role_assignments", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.StructureLayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StandardType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "SortOrder")
                        .IsUnique();

                    b.ToTable("structure_layers", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.StructureNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LeaderMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("LayerId");

                    b.HasIndex("LeaderMemberId");

                    b.HasIndex("ParentNodeId");

                    b.HasIndex("ChurchId", "ClientRequestId")
                        .IsUnique()
                        .HasFilter("\"ClientRequestId\" IS NOT NULL");

                    b.HasIndex("ChurchId", "LayerId");

                    b.HasIndex("ChurchId", "ParentNodeId");

                    b.ToTable("structure_nodes", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.StructureTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId")
                        .IsUnique();

                    b.ToTable("structure_templates", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.UnitJoinInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByAuthUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("NodeId")
                        .IsUnique();

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("unit_join_invites", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthSubject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ChurchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthSubject")
                        .IsUnique();

                    b.HasIndex("ChurchId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Administrators.ChurchAdministrator", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.Church", "Church")
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KairosPayHub.Api.Domain.Structure.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Church");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Attendance.AttendanceCellInvitee", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.Member", "GraduatedMember")
                        .WithMany()
                        .HasForeignKey("GraduatedMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KairosPayHub.Api.Domain.Structure.Member", "InvitedByMember")
                        .WithMany()
                        .HasForeignKey("InvitedByMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GraduatedMember");

                    b.Navigation("InvitedByMember");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Attendance.AttendanceEntry", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KairosPayHub.Api.Domain.Attendance.AttendanceOccurrence", "Occurrence")
                        .WithMany("Entries")
                        .HasForeignKey("OccurrenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Occurrence");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Attendance.AttendanceFirstTimer", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Attendance.AttendanceOccurrence", "Occurrence")
                        .WithMany()
                        .HasForeignKey("OccurrenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Occurrence");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Attendance.AttendanceInviteeEntry", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Attendance.AttendanceCellInvitee", "Invitee")
                        .WithMany()
                        .HasForeignKey("InviteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KairosPayHub.Api.Domain.Attendance.AttendanceOccurrence", "Occurrence")
                        .WithMany()
                        .HasForeignKey("OccurrenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invitee");

                    b.Navigation("Occurrence");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Attendance.AttendanceMeetingPack", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Attendance.AttendanceOccurrence", "Occurrence")
                        .WithOne("Pack")
                        .HasForeignKey("KairosPayHub.Api.Domain.Attendance.AttendanceMeetingPack", "OccurrenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Occurrence");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Attendance.AttendanceMeetingPackFile", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Attendance.AttendanceMeetingPack", "Pack")
                        .WithMany("Files")
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Attendance.AttendanceMeetingPackReceipt", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Attendance.AttendanceMeetingPack", "Pack")
                        .WithMany("Receipts")
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Attendance.AttendanceMeetingType", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.Church", "Church")
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KairosPayHub.Api.Domain.Structure.StructureLayer", "SubmissionLayer")
                        .WithMany()
                        .HasForeignKey("SubmissionLayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Church");

                    b.Navigation("SubmissionLayer");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Attendance.AttendanceMeetingTypeScopeNode", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Attendance.AttendanceMeetingType", "MeetingType")
                        .WithMany("ScopeNodes")
                        .HasForeignKey("MeetingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeetingType");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Attendance.AttendanceOccurrence", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Attendance.AttendanceMeetingType", "MeetingType")
                        .WithMany("Occurrences")
                        .HasForeignKey("MeetingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeetingType");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Attendance.AttendanceScopeSubmission", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Attendance.AttendanceOccurrence", "Occurrence")
                        .WithMany("ScopeSubmissions")
                        .HasForeignKey("OccurrenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Occurrence");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Church", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Organization", "Organization")
                        .WithMany("Churches")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Giving.Contribution", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KairosPayHub.Api.Domain.Giving.GivingProgram", "Program")
                        .WithMany("Contributions")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Giving.GivingProgram", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.Church", "Church")
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KairosPayHub.Api.Domain.Giving.GivingProgram", "ParentProgram")
                        .WithMany("ChildPrograms")
                        .HasForeignKey("ParentProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Church");

                    b.Navigation("ParentProgram");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Giving.GivingProgramScopeNode", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Giving.GivingProgram", "Program")
                        .WithMany("ScopeNodes")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Media.ChurchServiceRecording", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Media.ServiceRecordingCategory", "Category")
                        .WithMany("Recordings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KairosPayHub.Api.Domain.Structure.Church", "Church")
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KairosPayHub.Api.Domain.Media.ServiceRecordingSeries", "Series")
                        .WithMany("Recordings")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Church");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Media.ServiceRecordingCategory", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.Church", "Church")
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Church");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Media.ServiceRecordingSeries", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.Church", "Church")
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Church");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.Cell", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.Church", "Church")
                        .WithMany("Cells")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KairosPayHub.Api.Domain.Structure.Fellowship", "Fellowship")
                        .WithMany("Cells")
                        .HasForeignKey("ChurchId", "FellowshipId")
                        .HasPrincipalKey("ChurchId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Church");

                    b.Navigation("Fellowship");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.Fellowship", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.Church", "Church")
                        .WithMany("Fellowships")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KairosPayHub.Api.Domain.Structure.Pfcc", "Pfcc")
                        .WithMany("Fellowships")
                        .HasForeignKey("PfccId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Church");

                    b.Navigation("Pfcc");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.Member", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.Church", "Church")
                        .WithMany("Members")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KairosPayHub.Api.Domain.Structure.StructureNode", "ParentNode")
                        .WithMany("Members")
                        .HasForeignKey("ChurchId", "ParentNodeId")
                        .HasPrincipalKey("ChurchId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Church");

                    b.Navigation("ParentNode");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.Pfcc", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.Church", "Church")
                        .WithMany("Pfccs")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Church");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.RoleAssignment", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.Church", "Church")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KairosPayHub.Api.Domain.Structure.Cell", "ScopeCell")
                        .WithMany()
                        .HasForeignKey("ScopeCellId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KairosPayHub.Api.Domain.Structure.Fellowship", "ScopeFellowship")
                        .WithMany()
                        .HasForeignKey("ScopeFellowshipId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KairosPayHub.Api.Domain.Structure.StructureNode", "ScopeNode")
                        .WithMany()
                        .HasForeignKey("ScopeNodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KairosPayHub.Api.Domain.Structure.Pfcc", "ScopePfcc")
                        .WithMany()
                        .HasForeignKey("ScopePfccId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Church");

                    b.Navigation("ScopeCell");

                    b.Navigation("ScopeFellowship");

                    b.Navigation("ScopeNode");

                    b.Navigation("ScopePfcc");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.StructureLayer", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.StructureTemplate", "Template")
                        .WithMany("Layers")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.StructureNode", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.Church", "Church")
                        .WithMany("Nodes")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KairosPayHub.Api.Domain.Structure.StructureLayer", "Layer")
                        .WithMany("Nodes")
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KairosPayHub.Api.Domain.Structure.Member", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KairosPayHub.Api.Domain.Structure.StructureNode", "ParentNode")
                        .WithMany("Children")
                        .HasForeignKey("ChurchId", "ParentNodeId")
                        .HasPrincipalKey("ChurchId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Church");

                    b.Navigation("Layer");

                    b.Navigation("Leader");

                    b.Navigation("ParentNode");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.StructureTemplate", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Structure.Church", "Church")
                        .WithOne("Template")
                        .HasForeignKey("KairosPayHub.Api.Domain.Structure.StructureTemplate", "ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Church");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.User", b =>
                {
                    b.HasOne("KairosPayHub.Api.Domain.Church", "Church")
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KairosPayHub.Api.Domain.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Church");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("KairosPayHub.Api.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("KairosPayHub.Api.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KairosPayHub.Api.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("KairosPayHub.Api.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Attendance.AttendanceMeetingPack", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Attendance.AttendanceMeetingType", b =>
                {
                    b.Navigation("Occurrences");

                    b.Navigation("ScopeNodes");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Attendance.AttendanceOccurrence", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Pack");

                    b.Navigation("ScopeSubmissions");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Giving.GivingProgram", b =>
                {
                    b.Navigation("ChildPrograms");

                    b.Navigation("Contributions");

                    b.Navigation("ScopeNodes");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Media.ServiceRecordingCategory", b =>
                {
                    b.Navigation("Recordings");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Media.ServiceRecordingSeries", b =>
                {
                    b.Navigation("Recordings");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Organization", b =>
                {
                    b.Navigation("Churches");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.Church", b =>
                {
                    b.Navigation("Cells");

                    b.Navigation("Fellowships");

                    b.Navigation("Members");

                    b.Navigation("Nodes");

                    b.Navigation("Pfccs");

                    b.Navigation("RoleAssignments");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.Fellowship", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.Pfcc", b =>
                {
                    b.Navigation("Fellowships");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.StructureLayer", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.StructureNode", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("KairosPayHub.Api.Domain.Structure.StructureTemplate", b =>
                {
                    b.Navigation("Layers");
                });
#pragma warning restore 612, 618
        }
    }
}
